/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugaspbo;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author ROG GL552VX
 */
public class MasterData extends javax.swing.JFrame {
        Connection conn = null;
        ResultSet rs = null;
        ResultSet rsj = null;
        Connection connj = null;
        PreparedStatement pst = null;
    
    private static Connection koneksi; //Koneksi
    private DefaultTableModel model; //Model Tabel
    
    /**
     * Creates new form MasterData
     */
    public MasterData() {
        initComponents();
        model=new DefaultTableModel();
        this.jTable1.setModel(model);
        model.addColumn("Kode Booking");
        model.addColumn("Kode Member");
        model.addColumn("Kode Lapangan");
        model.addColumn("Kode Jadwal");
        model.addColumn("Kode Fasilitas");
        model.addColumn("Jumlah Fasilitas");
        model.addColumn("Jumlah DP");
        model.addColumn("Jumlah Pelunasan");
        conn = tugaspbo.koneksidb.ConnectDb();
        connj = tugaspbo.koneksidb.ConnectDb();
        UpdateTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtbooking = new javax.swing.JTextField();
        txtmember = new javax.swing.JTextField();
        txtlapangan = new javax.swing.JTextField();
        txtjadwal = new javax.swing.JTextField();
        txtfasilitas = new javax.swing.JTextField();
        txtjfasilitas = new javax.swing.JTextField();
        txtdp = new javax.swing.JTextField();
        txtpelunasan = new javax.swing.JTextField();
        cmbUpdate = new javax.swing.JButton();
        cmbAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cmbDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel1.setText("MASTER DATA PELUNASAN");

        jLabel2.setText("Kode Booking");

        jLabel3.setText("Kode Member");

        jLabel4.setText("Kode Lapangan");

        jLabel5.setText("Kode Jadwal");

        jLabel6.setText("Kode Fasilitas");

        jLabel7.setText("Jumlah Fasilitas");

        jLabel8.setText("Jumlah DP");

        jLabel9.setText("Jumlah Pelunasan");

        cmbUpdate.setText("Update");
        cmbUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbUpdateActionPerformed(evt);
            }
        });

        cmbAdd.setText("Add");
        cmbAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAddActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        cmbDelete.setText("Delete");
        cmbDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(426, 426, 426)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtdp, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjfasilitas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtfasilitas, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtjadwal, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtlapangan, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmember, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtbooking, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(230, 230, 230)
                                .addComponent(cmbAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(cmbUpdate)
                                .addGap(29, 29, 29)
                                .addComponent(cmbDelete)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtbooking, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtmember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtlapangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtjadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtfasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtjfasilitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtdp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtpelunasan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbAdd)
                    .addComponent(cmbUpdate)
                    .addComponent(cmbDelete))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void UpdateTabel(){
            try{
            String sql = "select * from pelunasan";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            conn = tugaspbo.koneksidb.ConnectDb();
            connj = tugaspbo.koneksidb.ConnectDb();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        
}
    
    
    private void cmbAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAddActionPerformed
        Connection conn = null;
        Statement stmt = null;
        String booking = txtbooking.getText();
        String member = txtmember.getText();
        String lapangan = txtlapangan.getText();
        String jadwal = txtjadwal.getText();   
        String fasilitas = txtfasilitas.getText();
        String jfasilitas = txtjfasilitas.getText();
        String dp = txtdp.getText();
        String pelunasan = txtpelunasan.getText();
            
        if (txtbooking.getText().equals("") ||  txtmember.getText().equals("") || txtlapangan.getText().equals("") || txtjadwal.getText().equals("") || txtfasilitas.getText().equals("") || txtjfasilitas.getText().equals("") ||txtdp.getText().equals("") ||txtpelunasan.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Data belum lengkap !");
        }
        else
        {     
          
            
            try
            {
                conn = tugaspbo.koneksidb.ConnectDb();
                stmt = conn.createStatement();
                stmt.executeUpdate("insert into pelunasan values('"+booking+"','"+member+"','"+lapangan+"','"+jadwal+"','"+fasilitas+"','"+jfasilitas+"','"+dp+"','"+pelunasan+"')");
                String pesan = ("Data telah berhasil ditambahkan");
                JOptionPane.showMessageDialog(null, pesan);
                rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                txtbooking.setText("");
                txtmember.setText("");
                txtlapangan.setText("");
                txtjadwal.setText("");
                txtfasilitas.setText("");
                txtjfasilitas.setText("");
                txtdp.setText("");
                txtpelunasan.setText("");
                txtbooking.requestFocus();
                ambildata();
            }
            
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
                JOptionPane.showMessageDialog(rootPane, "Data sudah tersedia!");
            }
        }
                
    }//GEN-LAST:event_cmbAddActionPerformed

int brs;
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if(evt.getClickCount()==1){
        brs=jTable1.rowAtPoint(evt.getPoint());
        txtbooking.setText(jTable1.getValueAt(brs, 0).toString());
        txtmember.setText(jTable1.getValueAt(brs, 1).toString());
        txtlapangan.setText(jTable1.getValueAt(brs, 2).toString());
        txtjadwal.setText(jTable1.getValueAt(brs, 3).toString());
        txtfasilitas.setText(jTable1.getValueAt(brs, 4).toString());
        txtjfasilitas.setText(jTable1.getValueAt(brs, 5).toString());
        txtdp.setText(jTable1.getValueAt(brs, 6).toString());
        txtpelunasan.setText(jTable1.getValueAt(brs, 7).toString());
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void cmbUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbUpdateActionPerformed
        Connection conn = null;
        Statement stmt = null;
        String booking = txtbooking.getText();
        String member = txtmember.getText();
        String lapangan = txtlapangan.getText();
        String jadwal = txtjadwal.getText();   
        String fasilitas = txtfasilitas.getText();
        String jfasilitas = txtjfasilitas.getText();
        String dp = txtdp.getText();
        String pelunasan = txtpelunasan.getText();
        
        if (txtbooking.getText().equals("") ||  txtmember.getText().equals("") || txtlapangan.getText().equals("") || txtjadwal.getText().equals("") || txtfasilitas.getText().equals("") || txtjfasilitas.getText().equals("") ||txtdp.getText().equals("") ||txtpelunasan.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih data !");
        }
        else
        {
       try{
            String updatetabel = ("UPDATE pelunasan SET kode_member = '"+member+"',kode_booking = '"+booking+"',kode_lapangan = '"+lapangan+"',kode_jadwal = '"+jadwal+"',kode_fasilitas = '"+fasilitas+"',jumlah_fasilitas = '"+jfasilitas+"',jumlah_dp= '"+dp+"',jumlah_pelunasan= '"+pelunasan+"' WHERE kode_booking = '"+txtbooking.getText()+"'");
            conn = tugaspbo.koneksidb.ConnectDb();
            stmt = conn.createStatement();  
            stmt.execute(updatetabel);         
            String pesan = ("Data telah berhasil diubah");
                JOptionPane.showMessageDialog(null, pesan);
                rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                txtbooking.setText("");
                txtmember.setText("");
                txtlapangan.setText("");
                txtjadwal.setText("");
                txtfasilitas.setText("");
                txtjfasilitas.setText("");
                txtdp.setText("");
                txtpelunasan.setText("");
                txtbooking.requestFocus();
                ambildata();
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan");
        }
        }
    }//GEN-LAST:event_cmbUpdateActionPerformed

    private void cmbDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDeleteActionPerformed
        Connection conn = null;
        Statement stmt = null;
        String booking = txtbooking.getText();
        String member = txtmember.getText();
        String lapangan = txtlapangan.getText();
        String jadwal = txtjadwal.getText();   
        String fasilitas = txtfasilitas.getText();
        String jfasilitas = txtjfasilitas.getText();
        String dp = txtdp.getText();
        String pelunasan = txtpelunasan.getText();
        
        if (txtbooking.getText().equals("") ||  txtmember.getText().equals("") || txtlapangan.getText().equals("") || txtjadwal.getText().equals("") || txtfasilitas.getText().equals("") || txtjfasilitas.getText().equals("") ||txtdp.getText().equals("") ||txtpelunasan.getText().equals("")){
            JOptionPane.showMessageDialog(rootPane, "Silahkan pilih data !");
        }
        else
        {
        
       
       try{
            String deletetabel = ("DELETE from pelunasan WHERE kode_booking = '"+txtbooking.getText()+"'"); 
            conn = tugaspbo.koneksidb.ConnectDb();
            stmt = conn.createStatement();  
            stmt.execute(deletetabel);         
            String pesan = ("Data telah berhasil dihapus");
                JOptionPane.showMessageDialog(null, pesan);
                rs = pst.executeQuery();
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                txtbooking.setText("");
                txtmember.setText("");
                txtlapangan.setText("");
                txtjadwal.setText("");
                txtfasilitas.setText("");
                txtjfasilitas.setText("");
                txtdp.setText("");
                txtpelunasan.setText("");
                txtbooking.requestFocus();
                ambildata();
          
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(rootPane, "Terjadi Kesalahan");
        }
        }
    }//GEN-LAST:event_cmbDeleteActionPerformed
    
    
    private void ambildata(){
            // Menghapus semua record di tabel
            model.getDataVector( ).removeAllElements( );
            model.fireTableDataChanged( );
        try{
           //membuat statemen pemanggilan data pada table class dari database
           Statement stat = (Statement) koneksidb.ConnectDb().createStatement( );
           String sql        = "Select * from pelunasan";
           ResultSet res   = stat.executeQuery(sql);

           //penelusuran baris pada tabel class dari database
           while(res.next ()){
                Object[] obj = new Object[8];
                obj[0] = res.getString("kode_booking"); 
                obj[1] = res.getString("kode_member");
                obj[2] = res.getString("kode_lapangan");
                obj[3] = res.getString("kode_jadwal");
                obj[4] = res.getString("kode_fasilitas");
                obj[5] = res.getString("jumlah_fasilitas");
                obj[6] = res.getString("jumlah_dp");
                obj[7] = res.getString("jumlah_pelunasan");
                model.addRow(obj);
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(null, err.getMessage() );
        }
    }
          
    
    private static Connection buka_koneksi() {
        ResultSet rs = null;
        PreparedStatement pst = null;
        if (koneksi==null) {
            try {
                String url="jdbc:mysql://localhost:3306/futsalpbo"; //nama database perpustakaan
                String user="root"; //user mysql
                String password=""; //password mysql

                DriverManager.registerDriver(new com.mysql.jdbc.Driver());
                koneksi=DriverManager.getConnection(url,user,password);
            }catch (SQLException t) {
                System.out.println("Error membuat koneksi");
            }
        }
     return koneksi;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MasterData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MasterData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MasterData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MasterData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MasterData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmbAdd;
    private javax.swing.JButton cmbDelete;
    private javax.swing.JButton cmbUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtbooking;
    private javax.swing.JTextField txtdp;
    private javax.swing.JTextField txtfasilitas;
    private javax.swing.JTextField txtjadwal;
    private javax.swing.JTextField txtjfasilitas;
    private javax.swing.JTextField txtlapangan;
    private javax.swing.JTextField txtmember;
    private javax.swing.JTextField txtpelunasan;
    // End of variables declaration//GEN-END:variables
}
